com:
  training:
    message: Hello World!!!
    connectionNo: 40
#    messaging:
#
#      ar:
#        enabled: false
#      en:
#        enabled: true



#spring:
#  profiles:
#    active:
#      - dev

